spring:
  application:
    name: admin

  profiles:
    active: local
    include: common

server:
  port: 8010
  servlet:
    context-path: /
    session:
      timeout: 30m #로그인 세션 유지 시간 (마지막 동작 기점)